/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Auction {
  auctionId: string
  imageTag: string
  endTime: string
  title: string
  highlights?: Array<CachedAssets>
  lots: Lots
}
export interface CachedAssets {
  url: string
}
export interface Auctions {
  auctions: Array<Auction>
}
export interface DynamicField {
  dynamicFieldId: string
  data?: Record<string, string>
}
export interface Lot {
  winningBidAmount?: number
  startingBid?: number
  dynamicFields: Array<DynamicField>
}
export interface Lots {
  lots: Array<Lot>
}
export interface ApiResponse {
  auctions: Auctions
}
export interface ResponseData {
  data: ApiResponse
}
export function getNewsletterAuctions(count?: number | undefined | null): Promise<Array<Auction>>
